_wandb:
    value:
        cli_version: 0.21.0
        e:
            3nfom0kprxhlavwgqbze56qfr544vjwg:
                codePath: data_patching.ipynb
                codePathLocal: data_patching.ipynb
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "510665232384"
                        used: "257021906944"
                email: arangan18@hotmail.com
                executable: c:\Users\shado\AppData\Local\Programs\Python\Python312\python.exe
                host: Asus
                memory:
                    total: "6387490816"
                os: Windows-11-10.0.26100-SP0
                program: c:\Users\shado\Documents\Master Thesis\INFORM_marine-main_new\INFORM_marine-main\data_patching.ipynb
                python: CPython 3.12.5
                root: c:\Users\shado\Documents\Master Thesis\INFORM_marine-main_new\INFORM_marine-main
                startedAt: "2025-08-26T11:13:19.073867Z"
                writerId: 3nfom0kprxhlavwgqbze56qfr544vjwg
        m: []
        python_version: 3.12.5
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 2
                - 16
            "4": 3.12.5
            "5": 0.21.0
            "8":
                - 1
                - 3
            "12": 0.21.0
            "13": windows-amd64
Weight_decay:
    value: 0.0001
batch_size:
    value: 64
epochs:
    value: 50
learning_rate:
    value: 1e-05
