_wandb:
    value:
        cli_version: 0.21.1
        e:
            8lidxcvi7pixdpose78hcpcnvbnnzygm:
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "510665232384"
                        used: "247952142336"
                email: arangan18@hotmail.com
                executable: c:\Users\shado\anaconda3\python.exe
                host: Asus
                memory:
                    total: "6387490816"
                os: Windows-10-10.0.26100-SP0
                program: <python with no main file>
                python: CPython 3.11.4
                root: c:\Users\shado\Documents\Master Thesis\INFORM_marine-main_new\INFORM_marine-main
                startedAt: "2025-08-25T08:00:58.040407Z"
                writerId: 8lidxcvi7pixdpose78hcpcnvbnnzygm
        m: []
        python_version: 3.11.4
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 2
                - 16
            "4": 3.11.4
            "5": 0.21.1
            "8":
                - 1
                - 3
            "12": 0.21.1
            "13": windows-amd64
Weight_decay:
    value: 0.0001
batch_size:
    value: 64
epochs:
    value: 50
learning_rate:
    value: 1e-05
