_wandb:
    value:
        cli_version: 0.21.1
        e:
            2tle4d4n712gwufz40eougndpvj7vblu:
                codePath: data_patching.ipynb
                codePathLocal: data_patching.ipynb
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "510665232384"
                        used: "263550824448"
                email: arangan18@hotmail.com
                executable: c:\Users\shado\anaconda3\python.exe
                host: Asus
                memory:
                    total: "6387490816"
                os: Windows-10-10.0.26100-SP0
                program: c:\Users\shado\Documents\Master Thesis\INFORM_marine-main_new\INFORM_marine-main\data_patching.ipynb
                python: CPython 3.11.4
                root: c:\Users\shado\Documents\Master Thesis\INFORM_marine-main_new\INFORM_marine-main
                startedAt: "2025-09-02T10:44:42.570183Z"
                writerId: 2tle4d4n712gwufz40eougndpvj7vblu
        m: []
        python_version: 3.11.4
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 2
                - 16
            "4": 3.11.4
            "5": 0.21.1
            "8":
                - 1
                - 3
            "12": 0.21.1
            "13": windows-amd64
Weight_decay:
    value: 0.0001
batch_size:
    value: 64
epochs:
    value: 20
learning_rate:
    value: 0.001
