_wandb:
    value:
        cli_version: 0.21.0
        e:
            4vn44sd15cdpcuhmp4a9kbep9szqyy1v:
                codePath: data_patching.ipynb
                codePathLocal: data_patching.ipynb
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "510665232384"
                        used: "255717699584"
                email: arangan18@hotmail.com
                executable: c:\Users\shado\AppData\Local\Programs\Python\Python312\python.exe
                host: Asus
                memory:
                    total: "6387490816"
                os: Windows-11-10.0.26100-SP0
                program: c:\Users\shado\Documents\Master Thesis\INFORM_marine-main_new\INFORM_marine-main\data_patching.ipynb
                python: CPython 3.12.5
                root: c:\Users\shado\Documents\Master Thesis\INFORM_marine-main_new\INFORM_marine-main
                startedAt: "2025-07-23T15:35:45.033769Z"
                writerId: 4vn44sd15cdpcuhmp4a9kbep9szqyy1v
        m: []
        python_version: 3.12.5
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 16
            "4": 3.12.5
            "5": 0.21.0
            "8":
                - 1
                - 3
            "12": 0.21.0
            "13": windows-amd64
batch_size:
    value: 64
epochs:
    value: 20
learning_rate:
    value: 0.001
model:
    value: ResNetAutoEncoder
